"""add_fsa_bridge_fields

Revision ID: 7d4944f5f4ac
Revises: e28cd7418010
Create Date: 2026-07-06 13:44:10.363610

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d4944f5f4ac'
down_revision: str | None = 'e28cd7418010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fsa_constraints', sa.Column('fiscal_year', sa.String(length=32), nullable=True))
    op.add_column('fsa_constraints', sa.Column('raw_source_name', sa.String(length=255), nullable=True))
    op.add_column('fsa_constraints', sa.Column('coal_company', sa.String(length=255), nullable=True))
    op.add_column(
        "fsa_constraints",
        sa.Column("quantity_lac_mt", sa.Numeric(precision=16, scale=4), nullable=True),
    )
    op.add_column(
        "fsa_constraints",
        sa.Column("quantity_mt", sa.Numeric(precision=16, scale=3), nullable=True),
    )
    op.add_column('fsa_constraints', sa.Column('valid_to', sa.Date(), nullable=True))
    op.add_column('fsa_constraints', sa.Column('remarks', sa.String(length=2000), nullable=True))
    op.add_column(
        "fsa_constraints",
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column('fsa_constraints', sa.Column('parser_notes', sa.String(length=2000), nullable=True))
    op.add_column('fsa_constraints', sa.Column('status', sa.String(length=32), nullable=False))

    op.alter_column('fsa_constraints', 'plant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fsa_constraints', 'annual_contract_quantity_mt',
               existing_type=sa.NUMERIC(precision=16, scale=3),
               nullable=True)
    op.alter_column('fsa_constraints', 'contract_start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('fsa_constraints', 'contract_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fsa_constraints', 'contract_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('fsa_constraints', 'contract_start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('fsa_constraints', 'annual_contract_quantity_mt',
               existing_type=sa.NUMERIC(precision=16, scale=3),
               nullable=False)
    op.alter_column('fsa_constraints', 'plant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('fsa_constraints', 'status')
    op.drop_column('fsa_constraints', 'parser_notes')
    op.drop_column('fsa_constraints', 'extraction_confidence')
    op.drop_column('fsa_constraints', 'remarks')
    op.drop_column('fsa_constraints', 'valid_to')
    op.drop_column('fsa_constraints', 'quantity_mt')
    op.drop_column('fsa_constraints', 'quantity_lac_mt')
    op.drop_column('fsa_constraints', 'coal_company')
    op.drop_column('fsa_constraints', 'raw_source_name')
    op.drop_column('fsa_constraints', 'fiscal_year')
    # ### end Alembic commands ###
