"""initial schema

Revision ID: e28cd7418010
Revises:
Create Date: 2026-07-06 01:46:38.494379

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e28cd7418010"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_table(
        "coal_companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "optimization_runs",
        sa.Column("run_timestamp", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("triggered_by", sa.String(length=32), nullable=False),
        sa.Column("solver_status", sa.String(length=32), nullable=True),
        sa.Column("total_estimated_cost", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("input_snapshot", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plants",
        sa.Column("plant_code", sa.String(length=32), nullable=False),
        sa.Column("plant_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plants_plant_code"), "plants", ["plant_code"], unique=True)
    op.create_table(
        "daily_stock",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("opening_stock_mt", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("receipt_mt", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("consumption_mt", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("closing_stock_mt", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("expected_closing_stock_mt", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("reconciliation_difference_mt", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("validation_status", sa.String(length=16), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plant_id", "report_date", name="uq_daily_stock_plant_date"),
    )
    op.create_index(op.f("ix_daily_stock_plant_id"), "daily_stock", ["plant_id"], unique=False)
    op.create_index(op.f("ix_daily_stock_report_date"), "daily_stock", ["report_date"], unique=False)
    op.create_table(
        "documents",
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False)
    op.create_index(op.f("ix_documents_sha256_hash"), "documents", ["sha256_hash"], unique=True)
    op.create_table(
        "plant_aliases",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("alias_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias_name", name="uq_plant_alias_name"),
    )
    op.create_index(op.f("ix_plant_aliases_alias_name"), "plant_aliases", ["alias_name"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("plant_id", sa.UUID(), nullable=True),
        sa.Column("recommendation_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["optimization_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=True),
        sa.Column("coal_company_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["coal_company_id"], ["coal_companies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "allocation_results",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("allocation_type", sa.String(length=32), nullable=False),
        sa.Column("quantity_mt", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("acq_utilization_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["optimization_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fsa_constraints",
        sa.Column("constraint_type", sa.String(length=32), nullable=False),
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("coal_company_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("annual_contract_quantity_mt", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("monthly_cap_mt", sa.Numeric(precision=16, scale=3), nullable=True),
        sa.Column("contract_start_date", sa.Date(), nullable=False),
        sa.Column("contract_end_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["coal_company_id"], ["coal_companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fsa_constraints_plant_id"), "fsa_constraints", ["plant_id"], unique=False)
    op.create_table(
        "landed_costs",
        sa.Column("plant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("basic_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("freight", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("taxes", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("other_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_landed_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_landed_costs_plant_id"), "landed_costs", ["plant_id"], unique=False)
    op.create_table(
        "variable_costs",
        sa.Column("plant_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_plant_name", sa.String(length=255), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("variable_cost_per_unit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_variable_costs_plant_id"), "variable_costs", ["plant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_variable_costs_plant_id"), table_name="variable_costs")
    op.drop_table("variable_costs")
    op.drop_index(op.f("ix_landed_costs_plant_id"), table_name="landed_costs")
    op.drop_table("landed_costs")
    op.drop_index(op.f("ix_fsa_constraints_plant_id"), table_name="fsa_constraints")
    op.drop_table("fsa_constraints")
    op.drop_table("allocation_results")
    op.drop_table("suppliers")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_plant_aliases_alias_name"), table_name="plant_aliases")
    op.drop_table("plant_aliases")
    op.drop_index(op.f("ix_documents_sha256_hash"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_daily_stock_report_date"), table_name="daily_stock")
    op.drop_index(op.f("ix_daily_stock_plant_id"), table_name="daily_stock")
    op.drop_table("daily_stock")
    op.drop_index(op.f("ix_plants_plant_code"), table_name="plants")
    op.drop_table("plants")
    op.drop_table("optimization_runs")
    op.drop_table("coal_companies")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
